trigger:
- main

pool:
  name: Default  # Uses pre-installed Maven & JDK, no sudo needed

steps:
# Step 1: Build your Java project and run tests
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

# # Step 2: Publish JUnit test results (shows tests in Azure UI)
# - task: PublishTestResults@2
#   inputs:
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     failTaskOnFailedTests: true

# # Optional Step 3: Publish JaCoCo code coverage report (if JaCoCo is configured)
# - task: PublishCodeCoverageResults@1
#   inputs:
#     codeCoverageTool: 'JaCoCo'
#     summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/target/site/jacoco/jacoco.xml'
#     reportDirectory: '$(System.DefaultWorkingDirectory)/**/target/site/jacoco'
